# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: hundred_eight_development
    <% if ENV["DB_HOST"].present? %>
    host: <%= ENV["DB_HOST"] %>
    username: <%= ENV.fetch("DB_USER", "postgres") %>
    password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
    <% end %>
  cable:
    <<: *default
    database: hundred_eight_development_cable
    <% if ENV["DB_HOST"].present? %>
    host: <%= ENV["DB_HOST"] %>
    username: <%= ENV.fetch("DB_USER", "postgres") %>
    password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
    <% end %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.rb

test:
  primary:
    <<: *default
    database: hundred_eight_test
    <% if ENV["DB_HOST"].present? %>
    host: <%= ENV["DB_HOST"] %>
    username: <%= ENV.fetch("DB_USER", "postgres") %>
    password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
    <% end %>
  cable:
    <<: *default
    database: hundred_eight_test_cable
    <% if ENV["DB_HOST"].present? %>
    host: <%= ENV["DB_HOST"] %>
    username: <%= ENV.fetch("DB_USER", "postgres") %>
    password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
    <% end %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.rb

production:
  primary: &primary_production
    <<: *default
    <% if ENV["DATABASE_URL"] %>
    url: <%= ENV["DATABASE_URL"] %>
    <% else %>
    database: hundred_eight_production
    username: hundred_eight
    password: <%= ENV["HUNDRED_EIGHT_DATABASE_PASSWORD"] %>
    <% end %>
  cache:
    <<: *primary_production
    <% unless ENV["DATABASE_URL"] %>
    database: hundred_eight_production_cache
    <% end %>
    migrations_paths: db/cache_migrate
    schema_dump: cache_schema.rb
  queue:
    <<: *primary_production
    <% unless ENV["DATABASE_URL"] %>
    database: hundred_eight_production_queue
    <% end %>
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.rb
  cable:
    <<: *primary_production
    <% unless ENV["DATABASE_URL"] %>
    database: hundred_eight_production_cable
    <% end %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.rb
